language: elixir

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

services:
- postgresql

env:
  global:
  - TEST_DATABASE_USER=postgres
  - TEST_DATABASE_PASS=

elixir: '1.8'

script:
- mix format --check-formatted
- mix test

notifications:
  email:
    on_success: never
