version: '3'
services:
  postgres:
    image: "postgres:11-alpine"
    environment:
    - POSTGRES_USER=ptolemy
    - POSTGRES_PASSWORD=imnotmeantforproduction
    - POSTGRES_DB=ptolemy_dev
    ports:
    - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    ports:
    - "5601:5601"
