name: Elixir CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: "22.0.7"
        elixir-version: "1.9.1"
    - run: mix deps.get
    - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:11-alpine"
        ports:
        - 5423:5432
        env:
          POSTGRES_USER: "tequila"
          POSTGRES_PASSWORD: "imnotmeantforproduction"
          POSTGRES_DB: "tequila_dev"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: "redislabs/redisearch:latest"
        ports:
        - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: "22.0.7"
        elixir-version: "1.9.1"
    - name: Install Dependencies
      run: |
        mix deps.get
        mix ecto.create
        mix ecto.migrate
        mix search_index
      env:
        MIX_ENV: test
        TEST_DATABASE_HOST: "postgres"
        REDIS_URL: "redis://redis:6379/0"
    - name: Run Tests
      run: mix test
      env:
        TEST_DATABASE_HOST: "postgres"
        REDIS_URL: "redis://redis:6379/0"
